/**
 * Generic GraphQL Types for Strapi 5 / Headless CMS
 */

import type { Nullable } from "@/types/common";
import type {
  ApiResult,
  PaginationInput,
  QueryOptions,
  SortOrder,
  StrapiFilters,
} from "@/types/api";

/**
 * Standard GraphQL variables container with optional filtering, pagination & locale
 */
export interface GqlVariables<TFilter = Record<string, unknown>> {
  filters?: StrapiFilters<TFilter>;
  pagination?: PaginationInput;
  sort?: SortOrder | SortOrder[];
  locale?: string;
  region?: string;
  slug?: string;
  [key: string]: unknown;
}

/**
 * Generic GraphQL Query Result for Strapi collection endpoints:
 * e.g. GqlCollection<HeaderItem, "headers"> -> { headers: HeaderItem[] }
 */
export type GqlCollection<TEntity, Key extends string = string> = {
  [K in Key]?: Nullable<TEntity[]>;
};

/**
 * Generic GraphQL Query Result for Strapi single-type endpoints:
 * e.g. GqlSingle<GlobalSetting, "globalSetting"> -> { globalSetting: GlobalSetting | null }
 */
export type GqlSingle<TEntity, Key extends string = string> = {
  [K in Key]?: Nullable<TEntity>;
};

/**
 * Type-safe Query Runner Interface generated by createQuery()
 */
export interface TypedQueryRunner<TData, TVariables = Record<string, unknown>> {
  /**
   * Directly executes the query and returns TData | null
   */
  (variables?: TVariables, options?: QueryOptions): Promise<TData | null>;

  /**
   * Safely executes query returning ApiResult<TData> (no uncaught throws)
   */
  safe: (variables?: TVariables, options?: QueryOptions) => Promise<ApiResult<TData>>;

  /**
   * Automatically unwraps a single item or the first element of an array
   */
  single: <TItem = unknown>(
    key: string,
    variables?: TVariables,
    options?: QueryOptions
  ) => Promise<TItem | null>;

  /**
   * Automatically unwraps a collection into a guaranteed safe array TItem[]
   */
  collection: <TItem = unknown>(
    key: string,
    variables?: TVariables,
    options?: QueryOptions
  ) => Promise<TItem[]>;

  /**
   * The raw GraphQL document query string
   */
  document: string;
}

/**
 * Type-safe Mutation Runner Interface generated by createMutation()
 */
export interface TypedMutationRunner<TData, TVariables = Record<string, unknown>> {
  (variables?: TVariables, options?: QueryOptions): Promise<ApiResult<TData>>;
  document: string;
}
